# Generated by Django 3.2.7 on 2021-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre_usuario',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=86, unique=True),
        ),
    ]
